# Generated by Django 4.2.23 on 2025-06-27 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='slides/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='slides/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Consultez vos résultats en toute simplicité', max_length=300)),
                ('description', models.TextField(default='Vérifiez les résultats du BAC, BEPC, CEPE depuis votre mobile. Rapide, sécurisé et officiel pour tous les élèves du Congo.', max_length=300)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_pages', to='core.slide')),
            ],
        ),
    ]
